#!/usr/bin/python3
import sys
import time
def fact(n)
for i in range(2, int(n**0.5)+1):
if n % i == 0:
return (i, n//i)
return None
if __name__ == "__main__":
if len(sys.argv) != 2:
print("Usage: factors <file>")
exit()
ipf = sys.argc[1]
try :
with open(ipf, 'r') as f:
except FileNotFoundError:
print("FILE NOT FOUNT")
exit()
start_time = time.time()
for j line in lines:
n = int(line.strip())
factors = fact(n)
if factors:
print(f"{n}{factors[0]}*{factors[1]}")
if time.time() - start_time >5:
print("TIME LIMIT ESCEEDE")
exit()
