#!/bin/bash
factors() {
    if [ "$#" -ne 3 ]; then
        input_args=("$@")
        arg_count=0
        product=1
        for arg in ${input_args[*]}; do
            if [ "$arg_count" -gt 1 ]; then
                product=$(echo "$arg * $product" | bc)
            fi
            arg_count=$((arg_count + 1))
        done
    else
        product=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ':' '=')

    result=$(echo "if ($product > $num1) 1 else 0" | bc)
    if ((result == 1)); then
        temp=$num1
        num1=$product
        product=$temp
    fi

    echo "$num$num1*$product"
}

if [ "$#" -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r line; do
        result=$(timeout 5 factor "$line")
        if [ $? -eq 124 ]; then
            echo "Timeout occurred for factor $line"
        else
            factors "$result"
        fi
    done < "$1"
fi

