#!/usr/bin/python3
import sys
import random
import time
def is_prime(n, p=20):
if n == 2 or n == 3:
return True
if n < 2 or n % 2 == 0:
return False
d = n - 1 
r = 0
while d % 2 ==0:
d //=2
r+= 1
for _ in range(r - 1):
x = pow(x, 2, n)
if x == n - 1:
break
else:
return True
if __name__ == "__main__":
if len(sys.argv) != 2:
print("Usage: rsa <file>")
exit')
ipf = sys.argv[1]
try:
with open(ipf, 'r') as f:
lines = f.readlines()
except FileNotFoundError:
print("FILE NOT FOUND")
exit()
start_time = time.time()
n = int(lines[0].strip())
for i in range(2, n//2):
if n % i == 0 and is_prime(i) and is_prime(n//i):
print(f"{n}={i}*{n//i}')
break
if time.time() - start_time > 5:
print("TIME LIMIT EXCEEDED")
exit()
